version: "3"
services:
  node-js:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /workspace
    volumes:
      - .:/workspace
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    ports: 
      - 8080:8080
    image: node-vue-image 
    container_name: node-vue-container 
    tty: true